"""Never ask a customer for the same document twice.

Two checklists, both built from the single list in document_requirements.py:

  * financing_checklist - the Bidii Credit documents. Anything already
    uploaded on the insurance application for the SAME quote is attached
    automatically (the logbook, ID and KRA PIN the customer just gave us),
    and the "insurance premium quote" is generated by us from the selected
    quote - the customer never has a file for that.
  * application_checklist - the insurance application's own documents.
    For a LOGGED-IN customer, identity documents (national ID, KRA PIN)
    from their earlier applications are reused.

Reuse copies the document's metadata into a new row pointing at the same
stored file - nothing is re-uploaded or duplicated in storage - and logs
an event so staff can see exactly where each file came from.

Security: a guest is identified only by a phone number, so cross-application
reuse of identity documents is allowed ONLY for an authenticated customer
whose id matches the application's customer. For everyone else only
documents tied to this exact quote are reused (they were uploaded in this
same journey). The customer is only ever told that a document is "on file"
- never shown its contents or filename.
"""

import hashlib
import logging
from collections import defaultdict
from datetime import datetime

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.storage import get_storage
from app.models.application import Application, ApplicationDocument, ApplicationEvent
from app.models.customer import Customer
from app.models.financing import FinancingApplication, FinancingDocument, FinancingEvent
from app.models.provider import InsuranceProvider
from app.models.quote import Quote, QuoteRequest
from app.services.document_requirements import (
    REUSABLE_ACROSS_APPLICATIONS,
    SYSTEM_PROVIDED_TYPES,
    DocumentSpec,
    financing_documents,
    insurance_documents,
)
from app.services.simple_pdf import render_text_pdf

logger = logging.getLogger("somosure.document_reuse")

SRC_INSURANCE = "Reused from insurance application"
SRC_EARLIER = "Reused from earlier application"
SRC_GENERATED = "Generated by Somosure"


def _source_from_notes(notes: str | None) -> str:
    if notes:
        if notes.startswith(SRC_INSURANCE):
            return "insurance_application"
        if notes.startswith(SRC_EARLIER):
            return "earlier_application"
        if notes.startswith(SRC_GENERATED):
            return "generated"
    return "uploaded"


def _item(spec: DocumentSpec, state: str, source: str | None = None) -> dict:
    return {
        "type": spec.type,
        "label": spec.label,
        "description": spec.description,
        "tips": list(spec.tips),
        "state": state,
        "source": source,
    }


def _pick_earliest(candidates: list[tuple[int, datetime, object, str]]):
    """The first-uploaded document wins; documents tied to this exact
    quote (priority 0) beat anything from elsewhere (priority 1)."""
    return min(candidates, key=lambda c: (c[0], c[1]))


def _money(value) -> str:
    return f"{value:,.2f}"


# --------------------------------------------------------------------------
# Financing
# --------------------------------------------------------------------------


async def _financing_candidates(
    db: AsyncSession, app: FinancingApplication, wanted: set[str], authed_customer_id: str | None
) -> dict[str, list[tuple[int, datetime, object, str]]]:
    found: dict[str, list[tuple[int, datetime, object, str]]] = defaultdict(list)

    same_quote_apps = (
        await db.scalars(
            select(Application).where(Application.quote_id == app.quote_id, Application.customer_id == app.customer_id)
        )
    ).all()
    same_quote_ids = [a.id for a in same_quote_apps]
    ref_by_id = {a.id: a.reference for a in same_quote_apps}
    if same_quote_ids:
        docs = (
            await db.scalars(
                select(ApplicationDocument).where(
                    ApplicationDocument.application_id.in_(same_quote_ids),
                    ApplicationDocument.document_type.in_(wanted),
                    ApplicationDocument.status != "rejected",
                )
            )
        ).all()
        for d in docs:
            found[d.document_type].append((0, d.uploaded_at, d, f"{SRC_INSURANCE} {ref_by_id[d.application_id]}"))

    if authed_customer_id and authed_customer_id == str(app.customer_id):
        stable = wanted & REUSABLE_ACROSS_APPLICATIONS
        if stable:
            prev_fin = (
                await db.scalars(
                    select(FinancingApplication).where(
                        FinancingApplication.customer_id == app.customer_id, FinancingApplication.id != app.id
                    )
                )
            ).all()
            fin_ref = {f.id: f.reference for f in prev_fin}
            if fin_ref:
                docs = (
                    await db.scalars(
                        select(FinancingDocument).where(
                            FinancingDocument.financing_application_id.in_(list(fin_ref)),
                            FinancingDocument.document_type.in_(stable),
                            FinancingDocument.status != "rejected",
                        )
                    )
                ).all()
                for d in docs:
                    found[d.document_type].append(
                        (1, d.uploaded_at, d, f"{SRC_EARLIER} {fin_ref[d.financing_application_id]}")
                    )

            other_stmt = select(Application).where(Application.customer_id == app.customer_id)
            if same_quote_ids:  # `NOT IN ()` / `NOT IN (NULL)` would match nothing, so only add it when non-empty
                other_stmt = other_stmt.where(Application.id.notin_(same_quote_ids))
            other_apps = (await db.scalars(other_stmt)).all()
            app_ref = {a.id: a.reference for a in other_apps}
            if app_ref:
                docs = (
                    await db.scalars(
                        select(ApplicationDocument).where(
                            ApplicationDocument.application_id.in_(list(app_ref)),
                            ApplicationDocument.document_type.in_(stable),
                            ApplicationDocument.status != "rejected",
                        )
                    )
                ).all()
                for d in docs:
                    found[d.document_type].append((1, d.uploaded_at, d, f"{SRC_EARLIER} {app_ref[d.application_id]}"))
    return found


async def _generate_premium_quote(db: AsyncSession, app: FinancingApplication) -> FinancingDocument | None:
    quote = await db.get(Quote, app.quote_id)
    if not quote:
        return None
    provider = await db.get(InsuranceProvider, quote.provider_id)
    request = await db.get(QuoteRequest, quote.quote_request_id)
    customer = await db.get(Customer, app.customer_id)
    answers = (request.input_data if request else None) or {}

    lines = [
        f"Quote reference: {request.reference if request else '-'}",
        f"Prepared for: {customer.full_name if customer else '-'}   Phone: {customer.phone if customer else '-'}",
        f"Insurer: {quote.underlying_provider_name or (provider.name if provider else '-')}",
        "",
    ]
    vehicle_bits = [
        str(answers.get(k))
        for k in ("registration_number", "make", "model", "year")
        if answers.get(k) not in (None, "")
    ]
    if vehicle_bits:
        lines.append("Vehicle: " + " ".join(vehicle_bits))
    if answers.get("cover_type"):
        lines.append(f"Cover type: {str(answers['cover_type']).replace('_', ' ')}")
    summary = (quote.coverage or {}).get("summary") if isinstance(quote.coverage, dict) else None
    if summary:
        lines.append(f"Cover: {summary}")
    cur = quote.currency or "KES"
    lines += [
        "",
        f"Premium: {cur} {_money(quote.premium)}",
        f"Taxes and levies: {cur} {_money(quote.taxes)}",
        f"Fees: {cur} {_money(quote.fees)}",
        f"TOTAL PAYABLE: {cur} {_money(quote.total)}",
        "",
        f"Financing application: {app.reference}",
    ]
    if quote.valid_until:
        lines.append(f"Quote valid until: {quote.valid_until:%d %b %Y}")
    if quote.is_mock:
        lines.append("NOTE: demonstration quote - not a real premium.")
    lines += ["", "Generated automatically by Somosure from the quote selected online."]

    pdf = render_text_pdf("Insurance premium quote", lines)
    storage_path = await get_storage().save(f"financing/{app.id}", "premium_quote.pdf", pdf)
    doc = FinancingDocument(
        financing_application_id=app.id,
        document_type="premium_quote",
        storage_path=storage_path,
        original_filename="premium_quote.pdf",
        content_type="application/pdf",
        size_bytes=len(pdf),
        status="uploaded",
        validation_notes=f"{SRC_GENERATED} from the selected quote.",
        file_hash=hashlib.sha256(pdf).hexdigest(),
    )
    db.add(doc)
    db.add(
        FinancingEvent(
            financing_application_id=app.id, event_type="document_generated", notes="Generated the insurance premium quote"
        )
    )
    return doc


async def financing_checklist(
    db: AsyncSession, application_id: str, *, attach: bool, authed_customer_id: str | None = None
) -> dict:
    app = await db.get(FinancingApplication, application_id)
    if not app:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Financing application not found")
    specs = financing_documents(app.is_corporate)

    async def own_docs() -> dict[str, FinancingDocument]:
        rows = (
            await db.scalars(
                select(FinancingDocument)
                .where(FinancingDocument.financing_application_id == app.id, FinancingDocument.status != "rejected")
                .order_by(FinancingDocument.uploaded_at.asc())
            )
        ).all()
        out: dict[str, FinancingDocument] = {}
        for r in rows:
            out.setdefault(r.document_type, r)
        return out

    have = await own_docs()

    if attach:
        wanted = {s.type for s in specs if s.type not in have and s.type not in SYSTEM_PROVIDED_TYPES}
        if wanted:
            candidates = await _financing_candidates(db, app, wanted, authed_customer_id)
            for spec in specs:
                options = candidates.get(spec.type)
                if spec.type not in wanted or not options:
                    continue
                _, _, src_doc, source = _pick_earliest(options)
                db.add(
                    FinancingDocument(
                        financing_application_id=app.id,
                        document_type=spec.type,
                        storage_path=src_doc.storage_path,
                        original_filename=src_doc.original_filename,
                        content_type=src_doc.content_type,
                        size_bytes=src_doc.size_bytes,
                        status=src_doc.status,
                        validation_notes=source[:500],
                        file_hash=getattr(src_doc, "file_hash", None),
                    )
                )
                db.add(
                    FinancingEvent(
                        financing_application_id=app.id,
                        event_type="document_reused",
                        notes=f"{spec.label} - {source[0].lower() + source[1:]}",
                    )
                )
        if "premium_quote" not in have:
            await _generate_premium_quote(db, app)
        await db.commit()
        have = await own_docs()

    items, missing = [], []
    for spec in specs:
        doc = have.get(spec.type)
        if doc:
            items.append(_item(spec, "provided", _source_from_notes(doc.validation_notes)))
        elif spec.type in SYSTEM_PROVIDED_TYPES:
            items.append(_item(spec, "auto", "generated"))
        else:
            items.append(_item(spec, "missing"))
            missing.append(spec.type)
    return {"items": items, "missing": missing, "complete": not missing}


# --------------------------------------------------------------------------
# Insurance application
# --------------------------------------------------------------------------


async def application_checklist(
    db: AsyncSession, application_id: str, *, attach: bool, authed_customer_id: str | None = None
) -> dict:
    app = await db.get(Application, application_id)
    if not app:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Application not found")

    quote = await db.get(Quote, app.quote_id)
    request = await db.get(QuoteRequest, quote.quote_request_id) if quote else None
    category = request.category if request else "motor"
    specs = insurance_documents(category)

    async def own_docs() -> dict[str, ApplicationDocument]:
        rows = (
            await db.scalars(
                select(ApplicationDocument)
                .where(ApplicationDocument.application_id == app.id, ApplicationDocument.status != "rejected")
                .order_by(ApplicationDocument.uploaded_at.asc())
            )
        ).all()
        out: dict[str, ApplicationDocument] = {}
        for r in rows:
            out.setdefault(r.document_type, r)
        return out

    have = await own_docs()

    if attach and authed_customer_id and authed_customer_id == str(app.customer_id):
        wanted = {s.type for s in specs if s.type in REUSABLE_ACROSS_APPLICATIONS and s.type not in have}
        if wanted:
            found: dict[str, list[tuple[int, datetime, object, str]]] = defaultdict(list)
            earlier_apps = (
                await db.scalars(
                    select(Application).where(Application.customer_id == app.customer_id, Application.id != app.id)
                )
            ).all()
            app_ref = {a.id: a.reference for a in earlier_apps}
            if app_ref:
                for d in (
                    await db.scalars(
                        select(ApplicationDocument).where(
                            ApplicationDocument.application_id.in_(list(app_ref)),
                            ApplicationDocument.document_type.in_(wanted),
                            ApplicationDocument.status != "rejected",
                        )
                    )
                ).all():
                    found[d.document_type].append((1, d.uploaded_at, d, f"{SRC_EARLIER} {app_ref[d.application_id]}"))
            prev_fin = (
                await db.scalars(select(FinancingApplication).where(FinancingApplication.customer_id == app.customer_id))
            ).all()
            fin_ref = {f.id: f.reference for f in prev_fin}
            if fin_ref:
                for d in (
                    await db.scalars(
                        select(FinancingDocument).where(
                            FinancingDocument.financing_application_id.in_(list(fin_ref)),
                            FinancingDocument.document_type.in_(wanted),
                            FinancingDocument.status != "rejected",
                        )
                    )
                ).all():
                    found[d.document_type].append(
                        (1, d.uploaded_at, d, f"{SRC_EARLIER} {fin_ref[d.financing_application_id]}")
                    )

            added = False
            for spec in specs:
                options = found.get(spec.type)
                if spec.type not in wanted or not options:
                    continue
                _, _, src_doc, source = _pick_earliest(options)
                db.add(
                    ApplicationDocument(
                        application_id=app.id,
                        document_type=spec.type,
                        storage_path=src_doc.storage_path,
                        original_filename=src_doc.original_filename,
                        content_type=src_doc.content_type,
                        size_bytes=src_doc.size_bytes,
                        status=src_doc.status,
                        validation_notes=source[:500],
                        file_hash=getattr(src_doc, "file_hash", None),
                    )
                )
                db.add(
                    ApplicationEvent(
                        application_id=app.id,
                        event_type="document_reused",
                        notes=f"{spec.label} - {source[0].lower() + source[1:]}",
                    )
                )
                added = True
            if added:
                if app.status == "draft":
                    app.status = "documents_required"
                await db.commit()
                have = await own_docs()

    items, missing = [], []
    for spec in specs:
        doc = have.get(spec.type)
        if doc:
            items.append(_item(spec, "provided", _source_from_notes(doc.validation_notes)))
        else:
            items.append(_item(spec, "missing"))
            missing.append(spec.type)
    return {"items": items, "missing": missing, "complete": not missing}
